version: '3.5'
services:
  db:
    container_name: secretaria-virtual-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: db_secretaria
      POSTGRES_USER: usr_secretaria
      POSTGRES_PASSWORD: psw_secretaria
    ports:
      - 5432:5432
    tty: true
    restart: on-failure
  api:
    container_name: secretaria-virtual-api
    build:
      './docker/.'
    image: secretaria-virtual-api:latest
    working_dir: /var/www/html/secretaria-virtual-api
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html/secretaria-virtual-api
      - ./docker/apache/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - db
    depends_on:
      - db
    tty: true
    restart: on-failure
